name: Build POS Kasir Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Ambil source code
        uses: actions/checkout@v4

      - name: Install dependensi Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-pip \
            python3-venv \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake

      - name: Install Python tools
        run: |
          python3 -m pip install --upgrade pip
          pip3 install --upgrade buildozer cython
          pip3 install "python-for-android==2024.1.21"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Simpan APK
        uses: actions/upload-artifact@v4
        with:
          name: POS-KASIR-APK
          path: bin/*.apk
